# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
COPY package*.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY src ./src
COPY public ./public
RUN npm run build

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built files and production deps
COPY --from=builder /app/dist ./dist
COPY package*.json ./
RUN npm install --production --ignore-scripts --prefer-offline
COPY public ./public

EXPOSE 8080
# Default command to start the MCP
CMD ["node","dist/index.js"]
